(function() {var implementors = {};
implementors["rusoto_core"] = [{text:"impl&lt;T, E&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_core/struct.RusotoFuture.html\" title=\"struct rusoto_core::RusotoFuture\">RusotoFuture</a>&lt;T, E&gt;",synthetic:false,types:["rusoto_core::future::RusotoFuture"]},{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_core/request/struct.BufferedHttpResponseFuture.html\" title=\"struct rusoto_core::request::BufferedHttpResponseFuture\">BufferedHttpResponseFuture</a>",synthetic:false,types:["rusoto_core::request::BufferedHttpResponseFuture"]},{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_core/request/struct.HttpClientFuture.html\" title=\"struct rusoto_core::request::HttpClientFuture\">HttpClientFuture</a>",synthetic:false,types:["rusoto_core::request::HttpClientFuture"]},{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_core/reactor/struct.RequestDispatcherFuture.html\" title=\"struct rusoto_core::reactor::RequestDispatcherFuture\">RequestDispatcherFuture</a>",synthetic:false,types:["rusoto_core::reactor::RequestDispatcherFuture"]},{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_core/reactor/struct.CredentialsProviderFuture.html\" title=\"struct rusoto_core::reactor::CredentialsProviderFuture\">CredentialsProviderFuture</a>",synthetic:false,types:["rusoto_core::reactor::CredentialsProviderFuture"]},];
implementors["rusoto_credential"] = [{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_credential/struct.ContainerProviderFuture.html\" title=\"struct rusoto_credential::ContainerProviderFuture\">ContainerProviderFuture</a>",synthetic:false,types:["rusoto_credential::container::ContainerProviderFuture"]},{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_credential/struct.EnvironmentProviderFuture.html\" title=\"struct rusoto_credential::EnvironmentProviderFuture\">EnvironmentProviderFuture</a>",synthetic:false,types:["rusoto_credential::environment::EnvironmentProviderFuture"]},{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_credential/struct.InstanceMetadataProviderFuture.html\" title=\"struct rusoto_credential::InstanceMetadataProviderFuture\">InstanceMetadataProviderFuture</a>",synthetic:false,types:["rusoto_credential::instance_metadata::InstanceMetadataProviderFuture"]},{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_credential/struct.ProfileProviderFuture.html\" title=\"struct rusoto_credential::ProfileProviderFuture\">ProfileProviderFuture</a>",synthetic:false,types:["rusoto_credential::profile::ProfileProviderFuture"]},{text:"impl&lt;P:&nbsp;<a class=\"trait\" href=\"rusoto_credential/trait.ProvideAwsCredentials.html\" title=\"trait rusoto_credential::ProvideAwsCredentials\">ProvideAwsCredentials</a> + 'static&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_credential/struct.AutoRefreshingProviderFuture.html\" title=\"struct rusoto_credential::AutoRefreshingProviderFuture\">AutoRefreshingProviderFuture</a>&lt;P&gt;",synthetic:false,types:["rusoto_credential::AutoRefreshingProviderFuture"]},{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"rusoto_credential/struct.ChainProviderFuture.html\" title=\"struct rusoto_credential::ChainProviderFuture\">ChainProviderFuture</a>",synthetic:false,types:["rusoto_credential::ChainProviderFuture"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
